### ISSUE TITLE
automate translations

### ISSUE THREAD

**Issue by cezaraugusto** [h5bp/Front-end-Developer-Interview-Questions#449]
from #435

> As far as I know, the electron-i18n project was very successful using Crowdin as a tool for translating the project. Accepting translation PRs means that we rely 100% on maintainers which usually do not speak the translated language. Having it open for live edits might have better eyes to review translations. I'm not familiar with the tool but this might take some work to automate things, but would be nice.

**Comment by kyungw00k** [comment]
In order to use [Crowdin](https://crowdin.com/), must do some stuff as below.

**TODO**
- [ ] Login `crowdin` service as `h5bp` account
- [ ] Integrate `Front-end-Developer-Interview-Questions` by using `GitHub Integration`
- [ ] [Request Open Source Project Setup](https://crowdin.com/page/open-source-project-setup-request)

**Comment by vvscode** [comment]
@roblarsen @darcyclarke  just remind about this, cause it might cover all translations PR's

**Comment by roblarsen** [comment]
Thanks @vvscode

**Comment by GabrielaSaboia** [comment]
Are you still looking for help in this matter?

**Comment by roblarsen** [comment]
@GabrielaSaboia Very much so. I would like to do a push to modernize the questions here, since some of them are feeling a little date, but I'm afraid to because of the work involved in translation.

**Comment by roblarsen** [comment]
We have two PRS

#742 which is the node/azure translations code to generate the translations
#743 which is an update to the static site to serve as a stopgap while we work out the workflow

We also have two (and eventually more) discussions

https://github.com/h5bp/Front-end-Developer-Interview-Questions/discussions

**Comment by roblarsen** [comment]
Must solve translation problem so we can edit the questions to reflect modern front end development and then I can feel good about the state of this 60k star repo. 

https://lokalise.com/
https://crowdin.com/
